version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181

  kafkaserver:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "notification:1:1:compact"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025 # SMTP server ports
      - 8025:8025 # Web UI ports

  postgres-keycloak:
    container_name: postgres-keycloak
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
      - ./keycloak/realms/realm-export.json:/tmp/realm-export.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8484:8080
    depends_on:
      - postgres-keycloak
    links:
     - "postgres-keycloak:postgres-keycloak"

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: setlistOrganizer
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: "${PGPORT}"
    volumes:
      - .:/var/lib/postgresql/data
    network_mode: host

  configserver:
    build: ./configserver
    image: configserver
    container_name: configserver
    ports:
      - 8071:8071
    environment:
      ENCRYPT_KEY: setlist-organizer-secret-key
    network_mode: host

  eurekaserver:
    build: ./eurekaserver
    image: eurekaserver
    container_name: eurekaserver
    ports:
      - 8070:8070
    environment:
      SPRING_CLOUD_CONFIG_FAIL_FAST: "${SPRING_CLOUD_CONFIG_FAIL_FAST}"
    depends_on:
      - configserver
    network_mode: host

  rest-app:
    build: ./rest-app
    image: docker-rest-app
    container_name: rest-app
    ports:
      - 8088:8088
    environment:
      SPRING_PROFILES_ACTIVE: postgres, jpa
      SPRING_CLOUD_CONFIG_URI: "${SPRING_CLOUD_CONFIG_URI}"
      SPRING_CLOUD_CONFIG_FAIL_FAST: "${SPRING_CLOUD_CONFIG_FAIL_FAST}"
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:${PGPORT}/setlistOrganizer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KEYCLOAK_REALM_CERT_URL: "${KEYCLOAK_REALM_CERT_URL}"
      KEYCLOAK_REALM_ISSUER_URL: "${KEYCLOAK_REALM_ISSUER_URL}"
      KEYCLOAK_REALM_TOKEN_URL: "${KEYCLOAK_REALM_TOKEN_URL}"
    depends_on:
      - postgres
      - keycloak
      - configserver
      - kafkaserver
    network_mode: host

  web-app:
    build: ./web-app
    image: docker-web-app
    container_name: web-app
    ports:
      - 8080:8080
    environment:
      SPRING_CLOUD_CONFIG_URI: "${SPRING_CLOUD_CONFIG_URI}"
      HOST_NAME: localhost
      KEYCLOAK_REALM_CERT_URL: "${KEYCLOAK_REALM_CERT_URL}"
      KEYCLOAK_REALM_ISSUER_URL: "${KEYCLOAK_REALM_ISSUER_URL}"
      KEYCLOAK_REALM_TOKEN_URL: "${KEYCLOAK_REALM_TOKEN_URL}"
    depends_on:
      - keycloak
  #    - rest-app
      - configserver
    network_mode: host

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./rest-app/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    network_mode: host


  grafana:
    build: ./rest-app/config
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./rest-app/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/jvm-micrometer_rev9.json"
    network_mode: host