version: "3"

services:

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: setlistOrganizer
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data

  rest-app:
    build: ./rest-app
    image: docker-rest-app
    container_name: rest-app
    ports:
      - 8088:8088
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  web-app:
    build: ./web-app
    image: docker-web-app
    container_name: web-app
    ports:
      - 8080:8080
    environment:
      HOST_NAME: rest-app
    depends_on:
      - rest-app
    network_mode: host

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./rest-app/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    network_mode: host

  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./rest-app/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    network_mode: host