version: "3"

services:
  rest-app:
    build: ./rest-app
    image: docker-rest-app
    container_name: rest-app
    ports:
      - "8088:8088"

  web-app:
    build: ./web-app
    image: docker-web-app
    container_name: web-app
    ports:
      - "8080:8080"
    depends_on:
      - rest-app

    network_mode: host

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./rest-app/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    network_mode: host

  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./rest-app/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus

    network_mode: host
