example:
  property: example property

app:
  httpClient: ApiClient

base:
  url: http://${HOST_NAME:localhost}:8088
rest:
  server:
    host: ${HOST_NAME:localhost}
    port: 8088
    protocol: http
logging:
  level:
    org.springframework.security: DEBUG
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${PORT:8080}


spring:
  http:
    multipart:
      enabled: true
    jackson:
      date-format: yyyy/MM/dd
    main:
      allow-bean-definition-overriding: true
      allow-circular-references: true
    mvc:
      hiddenmethod:
        filter:
          enabled: true
    profiles:
      active: dev
    servlet:
      multipart:
        max-file-size: 128MB
        max-request-size: 128MB

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_REALM_AUTH_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/auth}
            end_session_endpoint: ${KEYCLOAK_REALM_LOGOUT_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/logout}
            issuer-uri: ${KEYCLOAK_REALM_ISSUER_URL:http://localhost:8484/auth/realms/setlist_organizer_realm}
            token-uri: ${KEYCLOAK_REALM_TOKEN_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/token}
            pre-connection-check: ${KEYCLOAK_PRE_CONNECTION_CHECK:true}
            number-of-connection-attempts: ${KEYCLOAK_NUMBER_OF_CONNECTION_ATTEMPTS:5}
            timeout-between-connection-attempts: ${KEYCLOAK_TIMEOUT_BETWEEN_CONNECTION_ATTEMPTS:3}
        registration:
          keycloak:
            client-id: setlist_organizer_client
            use-resource-role-mappings: true
            principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metric, env