version: "3"

services:

  postgres-keycloak:
    container_name: postgresql-keycloak
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak-solo
    volumes:
      - ./realms/realm-export.json:/tmp/realm-export.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8484:8080
    depends_on:
      - postgres-keycloak
    links:
      - "postgres-keycloak:postgres-keycloak"