spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/setlistOrganizer
    username: postgres
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor}
