##Application dev configuration
base:
  url: http://${HOST_NAME:localhost}:8088
rest:
  server:
    host: ${HOST_NAME:localhost}
    port: 8088
    protocol: http
logging:
  level:
    org.springframework.security: DEBUG
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${PORT:8080}


spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/auth/realms/setlist_organizer_realm
        registration:
          keycloak:
            client-id: setlist_organizer_client
            client-secret: 2kciSwPQuIRhABJWMq4o6wJV01z5Cmss
            use-resource-role-mappings: true
            principal-attribute: preferred_username
