##Application dev configuration
base:
  url: http://${HOST_NAME:localhost}:8088
rest:
  server:
    host: ${HOST_NAME:localhost}
    port: 8088
    protocol: http
logging:
  level:
    org.springframework.security: DEBUG
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${PORT:8080}


spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            #http://localhost:8484/auth/realms/setlist_organizer_realm/.well-known/openid-configuration
            authorization-uri: ${KEYCLOAK_REALM_AUTH_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/auth}
            end_session_endpoint: ${KEYCLOAK_REALM_LOGOUT_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/logout}
            issuer-uri: ${KEYCLOAK_REALM_ISSUER_URL:http://localhost:8484/auth/realms/setlist_organizer_realm}
            token-uri: ${KEYCLOAK_REALM_TOKEN_URL:http://localhost:8484/auth/realms/setlist_organizer_realm/protocol/openid-connect/token}
        registration:
          keycloak:
            client-id: setlist_organizer_client
            client-secret: 2kciSwPQuIRhABJWMq4o6wJV01z5Cmss
            use-resource-role-mappings: true
            principal-attribute: preferred_username
